{{- $appDbUrl := "" }}
{{- $appDbHost := "" }}
{{- $appDbPort := "" }}
{{- with .Values.databases.observatory }}
  {{- if .internal }}
  {{- $appDbHost = (include "postgresql.servicename" $) }}
  {{- $appDbPort = 5432 }}
  {{- $appDbUrl = print $appDbHost ":" $appDbPort "/" .database }}
  {{- else }}
  {{- $appDbHost = .host }}
  {{- $appDbPort = .port }}
  {{- $appDbUrl = print .host ":" .port "/" .database }}
  {{- end }}
{{- end }}

{{- $analyticsDbUrl := print .Values.databases.analytics.host ":" .Values.databases.analytics.port "/" .Values.databases.analytics.database }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "observatory.fullname" . }}
  labels:
    {{- include "observatory.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "observatory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "observatory.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "observatory.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-app-db
          image: postgres:16-alpine
          command: ['sh', '-c', 
            'until pg_isready -h {{ $appDbHost }} -p {{ $appDbPort }}; 
            do echo waiting for database; sleep 2; done;']
        - name: wait-for-analytics-db
          image: postgres:16-alpine
          command: ['sh', '-c', 
            'until pg_isready -h {{ .Values.databases.analytics.host }} -p {{ .Values.databases.analytics.port }}; 
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ $appDbUrl }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.databases.observatory.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.databases.observatory.password }}
            - name: SERVER_PORT
              value: {{ .Values.app.port | quote }}
            - name: SAE_REDISSTREAMPREFIX
              value: {{ .Values.sae.redisStreamPrefix | quote }}
            - name: SAE_REDISHOST
              value: {{ .Values.sae.redisHost | quote }}
            - name: SAE_REDISPORT
              value: {{ .Values.sae.redisPort | quote }}
            - name: ANALYTICS_JOBRUNINTERVAL
              value: {{ .Values.analyticsJobRunInterval | quote }}
            - name: ANALYTICS_DATASOURCE_URL
              value: jdbc:postgresql://{{ $analyticsDbUrl }}
            - name: ANALYTICS_DATASOURCE_USERNAME
              value: {{ .Values.databases.analytics.username }}
            - name: ANALYTICS_DATASOURCE_PASSWORD
              value: {{ .Values.databases.analytics.password }}              

            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.app.context_path | quote }}
            {{- with .Values.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.app.context_path }}/monitoring/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.app.context_path }}/monitoring/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
