name: observatory

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: observatory
      POSTGRES_USER: observatory
      POSTGRES_PASSWORD: observatory
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U observatory']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - db:/var/lib/postgresql/data
      - ./sample_data/observatory.sql:/docker-entrypoint-initdb.d/observatory.sql
    ports:
      - "5434:5432"

  analytics:
    image: postgres:latest
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U analytics']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - analytics-db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./pgadmin/postgreslocal-servers-config.json:/pgadmin4/servers.json
    ports:
      - "5051:80"

volumes:
  db:
  pgadmin:
  analytics-db: