apiVersion: v2
name: observatory-chart
description: A Helm chart to deploy observatory to Kubernetes

type: application

version: ${project.version}

appVersion: "${project.version}"

dependencies:
  - name: postgresql
    version: "17.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: databases.observatory.internal