app:
  context_path: "/observatory"
  port: 8081

analyticsJobRunInterval: 2000

sae:
  redisStreamPrefix: geomapper
  redisHost: localhost
  redisPort: 6379

databases:
  observatory: 
    internal: true
    # `host` and `port` are only relevant if `internal` is `false`
    host: local.starwit.de
    port: 31222
    database: observatory
    username: observatory
    password: observatory
  analytics:
    host: local.starwit.de
    port: 31222
    database: analytics
    username: analytics
    password: analytics 
    isTimescale: false

ingress:
  enabled: false
  annotations: 
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - host: local.starwit.de
      paths:
        - path: /observatory
          pathType: ImplementationSpecific
  tls: 
    - secretName: local.starwit.de
      hosts:
        - local.starwit.de